name: SDS210_ZuriWieNeu
channels:
  - conda-forge
  - defaults
dependencies:
  # Kern-Python und Jupyter-Infrastruktur
  - python=3.11
  - jupyterlab
  - ipykernel

  # Datenverarbeitung & Analyse (Schnelles Laden, Tabellen, DBSCAN)
  - pandas
  - geopandas
  - (pyogrio)          # Beschleunigt das Laden von gpkg-Dateien extrem
  - scikit-learn

  # Visualisierung & Interaktive Karten
  - matplotlib
  - folium
  - mapclassify      # Zwingend notwendig für geopandas.explore()